swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: smtp
    host: smtp.gmail.com
    port: 587
    encryption: tls
    auth_mode: login
    username: postuli.tn@gmail.com
    password: postulitn2023
