vich_uploader:
    db_driver: orm
    mappings:
        Guidesentretiens_files:
            uri_prefix:         /uploads/Guidesentretiens
            upload_destination: '%kernel.project_dir%/public/uploads/Guidesentretiens'
            namer:              Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_update:   true
            delete_on_remove:   true