#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_projets_detail:
    path: '/projets/{idProjet}'
    controller: 'App\Controller\ProjetsController::details'
    methods: ['GET']